Group.delete_all
Team.delete_all
Player.delete_all
TeamPlayer.delete_all

gA = Group.create(name: 'Group A')
gB = Group.create(name: 'Group B')

a1 = Country.create(name: 'Czech Republic', code: 'CZE', group_id: gA.id)
a2 = Country.create(name: 'Denmark', code: 'DEN', group_id: gA.id)
a3 = Country.create(name: 'Germany', code: 'GER', group_id: gA.id)
a4 = Country.create(name: 'Serbia', code: 'SRB', group_id: gA.id)
b1 = Country.create(name: 'England', code: 'ENG', group_id: gB.id)
b2 = Country.create(name: 'Italy', code: 'ITA', group_id: gB.id)
b3 = Country.create(name: 'Portugal', code: 'POR', group_id: gB.id)
b4 = Country.create(name: 'Sweden', code: 'SWE', group_id: gB.id)

g1 = Player.create(name: 'Marc-André ter Stegen', position: 'GK', age: 23, club: 'FC Barcelona', image: '', height: 1.87, nation: a3.name)
g2 = Player.create(name: 'Matthias Ginter', position: 'CB', age: 21, club: 'Borussia Dortmund', image: '', height: 1.88, nation: a3.name)
g3 = Player.create(name: 'Robin Knoche', position: 'CB', age: 23, club: 'VfL Wolfsburg', image: '', height: 1.90, nation: a3.name)
g4 = Player.create(name: 'Christian Günter', position: 'LB', age: 22, club: 'SC Freiburg', image: '', height: 1.84, nation: a3.name)
g5 = Player.create(name: 'Julian Korb', position: 'RB', age: 23, club: 'Borussia Mönchengladbach', image: '', height: 1.77, nation: a3.name)
g6 = Player.create(name: 'Emre Can', position: 'MF', age: 21, club: 'Liverpool F.C.', image: '', height: 1.84, nation: a3.name)
g7 = Player.create(name: 'Moritz Leitner', position: 'MF', age: 22, club: 'VfB Stuttgart', image: '', height: 1.76, nation: a3.name)
g8 = Player.create(name: 'Leonardo Bittencourt', position:'MF', age: 21, club: 'Hannover 96', image: '', height: 1.71, nation: a3.name)
g9 = Player.create(name: 'Max Meyer', position: 'MF', age: 19, club: 'Schalke 04', image: '', height: 1.73, nation: a3.name)
g10 = Player.create(name: 'Maximilian Arnold', position: 'MF', age: 21, club: 'VfL Wolfsburg', image: '', height: 1.83, nation: a3.name)
g11 = Player.create(name: 'Kevin Volland', position: 'ST', age: 22, club: '1899 Hoffenheim', image: '', height: 1.79, nation: a3.name)

i1 = Player.create(name: 'Francesco Bardi', position: 'GK', age: 23, club: 'Inter Milan', image: '', height: 1.88, nation: b2.name)
i2 = Player.create(name: 'Daniele Rugani', position: 'CB', age: 20, club: 'Juventus', image: '', height: 1.88, nation: b2.name)
i3 = Player.create(name: 'Alessio Romagnoli', position: 'CB', age: 20, club: 'Roma', image: '', height: 1.88, nation: b2.name)
i4 = Player.create(name: 'Cristiano Biraghi', position: 'LB', age: 22, club: 'Inter Milan', image: '', height: 1.76, nation: b2.name)
i5 = Player.create(name: 'Davide Zappacosta', position: 'RB', age: 22, club: 'Atalanta', image: '', height: 1.82, nation: b2.name)
i6 = Player.create(name: 'Cristian Battocchio', position: 'MF', age: 23, club: 'Watford', image: '', height: 1.69, nation: b2.name)
i7 = Player.create(name: 'Lorenzo Crisetig', position: 'MF', age: 22, club: 'Inter Milan', image: '', height: 1.83, nation: b2.name)
i8 = Player.create(name: 'Stefano Sturaro', position:'MF', age: 22, club: 'Juventus', image: '', height: 1.82, nation: b2.name)
i9 = Player.create(name: 'Domenico Berardi', position: 'MF', age: 20, club: 'Juventus', image: '', height: 1.85, nation: b2.name)
i10 = Player.create(name: 'Marcello Trotta', position: 'ST', age: 22, club: 'Avellino', image: '', height: 1.87, nation: b2.name)
i11 = Player.create(name: 'Andrea Belotti', position: 'ST', age: 21, club: 'Palermo', image: '', height: 1.81, nation: b2.name)

e1 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e2 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e3 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e4 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e5 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e6 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e7 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e8 = Player.create(name: '', position:'', age: '', club: '', image: '', height: '', nation: b1.name)
e9 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e10 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)
e11 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b1.name)

p1 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p2 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p3 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p4 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p5 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p6 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p7 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p8 = Player.create(name: '', position:'', age: '', club: '', image: '', height: '', nation: b3.name)
p9 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p10 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)
p11 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b3.name)

w1 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w2 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w3 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w4 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w5 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w6 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w7 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w8 = Player.create(name: '', position:'', age: '', club: '', image: '', height: '', nation: b4.name)
w9 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w10 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)
w11 = Player.create(name: '', position: '', age: '', club: '', image: '', height: '', nation: b4.name)


t1.team_players.create(player_id: p1.id)
t2.team_players.create(player_id: p4.id)
t3.team_players.create(player_id: p2.id)
t4.team_players.create(player_id: p3.id)
t5.team_players.create(player_id: p2.id)
t6.team_players.create(player_id: p1.id)
t7.team_players.create(player_id: p3.id)
t8.team_players.create(player_id: p4.id)
t2.team_players.create(player_id: p5.id)
t4.team_players.create(player_id: p5.id)
t2.team_players.create(player_id: p6.id)
t3.team_players.create(player_id: p6.id)
t2.team_players.create(player_id: p7.id)
t6.team_players.create(player_id: p7.id)
t2.team_players.create(player_id: p8.id)
t7.team_players.create(player_id: p8.id)
t4.team_players.create(player_id: p9.id)
t5.team_players.create(player_id: p9.id)
t7.team_players.create(player_id: p10.id)
t4.team_players.create(player_id: p10.id)
t9.team_players.create(player_id: p11.id)
t2.team_players.create(player_id: p11.id)
t4.team_players.create(player_id: p12.id)
t9.team_players.create(player_id: p12.id)
