Group.delete_all
Team.delete_all
Player.delete_all
TeamPlayer.delete_all

gA = Group.create(name: 'Group A')
gB = Group.create(name: 'Group B')

a1 = Team.create(name: 'Czech Republic', code: 'CZE', group_id: gA.id, played: 0, wins: 0, draws: 0, losses: 0, points: 0)
a2 = Team.create(name: 'Denmark', code: 'DEN', group_id: gA.id, played: 0, wins: 0, draws: 0, losses: 0, points: 0)
a3 = Team.create(name: 'Germany', code: 'GER', group_id: gA.id, played: 0, wins: 0, draws: 0, losses: 0, points: 0)
a4 = Team.create(name: 'Serbia', code: 'SRB', group_id: gA.id, played: 0, wins: 0, draws: 0, losses: 0, points: 0)
b1 = Team.create(name: 'England', code: 'ENG', group_id: gB.id, played: 0, wins: 0, draws: 0, losses: 0, points: 0)
b2 = Team.create(name: 'Italy', code: 'ITA', group_id: gB.id, played: 0, wins: 0, draws: 0, losses: 0, points: 0)
b3 = Team.create(name: 'Portugal', code: 'POR', group_id: gB.id, played: 0, wins: 0, draws: 0, losses: 0, points: 0)
b4 = Team.create(name: 'Sweden', code: 'SWE', group_id: gB.id, played: 0, wins: 0, draws: 0, losses: 0, points: 0)

c1 = Player.create(name: 'Tomáš Koubek', position: 'GK', age: 22, club: 'Hradec Králové', image: '', height: 1.98, nation: a1.name)
c2 = Player.create(name: 'Pavel Kadeřábek', position: 'RB', age: 23, club: 'Sparta Prague', image: '', height: 1.82, nation: a1.name)
c3 = Player.create(name: 'Tomáš Kalas', position: 'CB', age: 22, club: 'Middlesbrough', image: '', height: 1.84, nation: a1.name)
c4 = Player.create(name: 'Jakub Brabec', position: 'CB', age: 22, club: 'Sparta Prague', image: '', height: 1.81, nation: a1.name)
c5 = Player.create(name: 'Matěj Hybš', position: 'LB', age: 22, club: 'Vysočina Jihlava', image: '', height: 1.81, nation: a1.name)
c6 = Player.create(name: 'Jaromír Zmrhal', position: 'MF', age: 21, club: 'Slavia Prague', image: '', height: 1.89, nation: a1.name)
c7 = Player.create(name: 'David Houska', position: 'MF', age: 21, club: 'Sigma Olomouc', image: '', height: 1.76, nation: a1.name)
c8 = Player.create(name: 'Tomáš Přikryl', position: 'MF', age: 22, club: 'FK Dukla Prague', image: '', height: 1.78, nation: a1.name)
c9 = Player.create(name: 'Ladislav Krejčí', position: 'MF', age: 22, club: 'Sparta Prague', image: '', height: 1.79, nation: a1.name)
c10 = Player.create(name: 'Jiří Skalák', position: 'ST', age: 23, club: 'Mladá Boleslav', image: '', height: 1.76, nation: a1.name)
c11 = Player.create(name: 'Václav Kadlec', position: 'ST', age: 23, club: 'Sparta Prague', image: '', height: 1.80, nation: a1.name)

d1 = Player.create(name: 'Jakob Busk', position: 'GK', age: 21, club: 'Sandefjord', image: '', height: 1.89, nation: a2.name)
d2 = Player.create(name: 'Alexander Scholz', position: 'RB', age: 22, club: 'Standard Liége', image: '', height: 1.89, nation: a2.name)
d3 = Player.create(name: 'Jannik Vestergaard', position: 'CB', age: 22, club: 'Werder Bremen', image: '', height: 1.99, nation: a2.name)
d4 = Player.create(name: 'Jores Okore', position: 'CB', age: 22, club: 'Aston Villa', image: '', height: 1.83, nation: a2.name)
d5 = Player.create(name: 'Jonas Knudsen', position: 'LB', age: 22, club: 'Esbjerg', image: '', height: 1.85, nation: a2.name)
d6 = Player.create(name: 'Andreas Christensen', position: 'MF', age: 19, club: 'Chelsea', image: '', height: 1.88, nation: a2.name)
d7 = Player.create(name: 'Lasse Vigen Christensen', position: 'MF', age: 20, club: 'Fulham', image: '', height: 1.78, nation: a2.name)
d8 = Player.create(name: 'Pierre Højbjerg', position: 'MF', age: 19, club: 'Bayern Munich', image: '', height: 1.85, nation: a2.name)
d9 = Player.create(name: 'Pione Sisto', position: 'MF', age: 20, club: 'FC Midtjylland', image: '', height: 1.71, nation: a2.name)
d10 = Player.create(name: 'Viktor Fischer', position: 'ST', age: 20, club: 'Ajax', image: '', height: 1.80, nation: a2.name)
d11 = Player.create(name: 'Yussuf Poulsen', position: 'ST', age: 20, club: 'RB Leipzig', image: '', height: 1.93, nation: a2.name)

g1 = Player.create(name: 'Marc-André ter Stegen', position: 'GK', age: 23, club: 'FC Barcelona', image: '', height: 1.87, nation: a3.name)
g5 = Player.create(name: 'Julian Korb', position: 'RB', age: 23, club: 'Borussia Mönchengladbach', image: '', height: 1.77, nation: a3.name)
g2 = Player.create(name: 'Matthias Ginter', position: 'CB', age: 21, club: 'Borussia Dortmund', image: '', height: 1.88, nation: a3.name)
g3 = Player.create(name: 'Robin Knoche', position: 'CB', age: 23, club: 'VfL Wolfsburg', image: '', height: 1.90, nation: a3.name)
g4 = Player.create(name: 'Christian Günter', position: 'LB', age: 22, club: 'SC Freiburg', image: '', height: 1.84, nation: a3.name)
g6 = Player.create(name: 'Emre Can', position: 'MF', age: 21, club: 'Liverpool F.C.', image: '', height: 1.84, nation: a3.name)
g7 = Player.create(name: 'Moritz Leitner', position: 'MF', age: 22, club: 'VfB Stuttgart', image: '', height: 1.76, nation: a3.name)
g8 = Player.create(name: 'Leonardo Bittencourt', position:'MF', age: 21, club: 'Hannover 96', image: '', height: 1.71, nation: a3.name)
g9 = Player.create(name: 'Max Meyer', position: 'MF', age: 19, club: 'Schalke 04', image: '', height: 1.73, nation: a3.name)
g10 = Player.create(name: 'Maximilian Arnold', position: 'MF', age: 21, club: 'VfL Wolfsburg', image: '', height: 1.83, nation: a3.name)
g11 = Player.create(name: 'Kevin Volland', position: 'ST', age: 22, club: '1899 Hoffenheim', image: '', height: 1.79, nation: a3.name)

e1 = Player.create(name: 'Jack Butland', position: 'GK', age: 22, club: 'Stoke City', image: '', height: 1.96, nation: b1.name)
e5 = Player.create(name: 'Carl Jenkinson', position: 'RB', age: 23, club: 'Arsenal', image: '', height: 1.85, nation: b1.name)
e2 = Player.create(name: 'John Stones', position: 'CB', age: 21, club: 'Everton', image: '', height: 1.88, nation: b1.name)
e3 = Player.create(name: 'Calum Chambers', position: 'CB', age: 20, club: 'Arsenal', image: '', height: 1.83, nation: b1.name)
e4 = Player.create(name: 'Luke Garbutt', position: 'LB', age: 22, club: 'Everton', image: '', height: 1.79, nation: b1.name)
e6 = Player.create(name: 'James Ward-Prowse', position: 'MF', age: 20, club: 'Southampton', image: '', height: 1.73, nation: b1.name)
e7 = Player.create(name: 'Jake Forster-Caskey', position: 'MF', age: 21, club: 'Brighton & Hove Albion', image: '', height: 1.78, nation: b1.name)
e8 = Player.create(name: 'Nathan Redmond', position: 'MF', age: 21, club: 'Norwich City', image: '', height: 1.73, nation: b1.name)
e9 = Player.create(name: 'Will Hughes', position: 'MF', age: 20, club: 'Derby County', image: '', height: 1.85, nation: b1.name)
e10 = Player.create(name: 'Danny Ings', position: 'ST', age: 22, club: 'Burnley', image: '', height: 1.78, nation: b1.name)
e11 = Player.create(name: 'Harry Kane', position: 'ST', age: 21, club: 'Tottenham Hotspur', image: '', height: 1.88, nation: b1.name)

i1 = Player.create(name: 'Francesco Bardi', position: 'GK', age: 23, club: 'Inter Milan', image: '', height: 1.88, nation: b2.name)
i5 = Player.create(name: 'Davide Zappacosta', position: 'RB', age: 22, club: 'Atalanta', image: '', height: 1.82, nation: b2.name)
i2 = Player.create(name: 'Daniele Rugani', position: 'CB', age: 20, club: 'Juventus', image: '', height: 1.88, nation: b2.name)
i3 = Player.create(name: 'Alessio Romagnoli', position: 'CB', age: 20, club: 'Roma', image: '', height: 1.88, nation: b2.name)
i4 = Player.create(name: 'Cristiano Biraghi', position: 'LB', age: 22, club: 'Inter Milan', image: '', height: 1.76, nation: b2.name)
i6 = Player.create(name: 'Cristian Battocchio', position: 'MF', age: 23, club: 'Watford', image: '', height: 1.69, nation: b2.name)
i7 = Player.create(name: 'Lorenzo Crisetig', position: 'MF', age: 22, club: 'Inter Milan', image: '', height: 1.83, nation: b2.name)
i8 = Player.create(name: 'Stefano Sturaro', position:'MF', age: 22, club: 'Juventus', image: '', height: 1.82, nation: b2.name)
i9 = Player.create(name: 'Domenico Berardi', position: 'MF', age: 20, club: 'Juventus', image: '', height: 1.85, nation: b2.name)
i10 = Player.create(name: 'Marcello Trotta', position: 'ST', age: 22, club: 'Avellino', image: '', height: 1.87, nation: b2.name)
i11 = Player.create(name: 'Andrea Belotti', position: 'ST', age: 21, club: 'Palermo', image: '', height: 1.81, nation: b2.name)

p1 = Player.create(name: 'José Sá', position: 'GK', age: 22, club: 'Maritimo', image: '', height: 1.92, nation: b3.name)
p5 = Player.create(name: 'Ricardo Esgaio', position: 'RB', age: 22, club: 'Académica', image: '', height: 1.71, nation: b3.name)
p2 = Player.create(name: 'Paulo Oliveira', position: 'CB', age: 23, club: 'Sporting CP', image: '', height: 1.87, nation: b3.name)
p3 = Player.create(name: 'Tiago Ilori', position: 'CB', age: 22, club: 'Bordeaux', image: '', height: 1.90, nation: b3.name)
p4 = Player.create(name: 'João Cancelo', position: 'LB', age: 21, club: 'Valencia', image: '', height: 1.82, nation: b3.name)
p6 = Player.create(name: 'Rafa Silva', position: 'MF', age: 22, club: 'SC Braga', image: '', height: 1.70, nation: b3.name)
p7 = Player.create(name: 'Bernardo Silva', position: 'MF', age: 20, club: 'Monaco', image: '', height: 1.73, nation: b3.name)
p8 = Player.create(name: 'William Carvalho', position:'MF', age: 23, club: 'Sporting CP', image: '', height: 1.87, nation: b3.name)
p9 = Player.create(name: 'Ivan Cavaleiro', position: 'MF', age: 21, club: 'Deportivo de La Coruña', image: '', height: 1.75, nation: b3.name)
p10 = Player.create(name: 'Rúben Neves', position: 'MF', age: 18, club: 'FC Porto', image: '', height: 1.80, nation: b3.name)
p11 = Player.create(name: 'Carlos Mané', position: 'ST', age: 21, club: 'Sporting CP', image: '', height: 1.72, nation: b3.name)

w1 = Player.create(name: 'Patrik Carlgren', position: 'GK', age: 23, club: 'AIK', image: '', height: 1.88, nation: b4.name)
w5 = Player.create(name: 'Emil Krafth', position: 'RB', age: 20, club: 'Helsingborgs IF', image: '', height: 1.81, nation: b4.name)
w2 = Player.create(name: 'Alexander Milošević', position: 'CB', age: 23, club: 'Beşiktaş', image: '', height: 1.91, nation: b4.name)
w3 = Player.create(name: 'Joseph Baffo', position: 'CB', age: 22, club: '', image: '', height: 1.85, nation: b4.name)
w4 = Player.create(name: 'Ludwig Augustinsson', position: 'LB', age: 21, club: 'Copenhagen', image: '', height: 1.81, nation: b4.name)
w6 = Player.create(name: 'Oscar Hiljemark', position: 'MF', age: 22, club: 'PSV', image: '', height: 1.84, nation: b4.name)
w7 = Player.create(name: 'Oscar Lewicki', position: 'MF', age: 22, club: 'Malmö FF', image: '', height: 1.75, nation: b4.name)
w8 = Player.create(name: 'Robin Quaison', position: 'MF', age: 21, club: 'Palermo', image: '', height: 1.80, nation: b4.name)
w9 = Player.create(name: 'Arber Zeneli', position: 'MF', age: 20, club: 'IF Elfsborg', image: '', height: 1.76, nation: b4.name)
w10 = Player.create(name: 'Branimir Hrgota', position: 'ST', age: 22, club: 'Borussia Mönchengladbach', image: '', height: 1.82, nation: b4.name)
w11 = Player.create(name: 'John Guidetti', position: 'ST', age: 23, club: 'Celtic', image: '', height: 1.85, nation: b4.name)

a1.team_players.create(player_id: c1.id)
a1.team_players.create(player_id: c2.id)
a1.team_players.create(player_id: c3.id)
a1.team_players.create(player_id: c4.id)
a1.team_players.create(player_id: c5.id)
a1.team_players.create(player_id: c6.id)
a1.team_players.create(player_id: c7.id)
a1.team_players.create(player_id: c8.id)
a1.team_players.create(player_id: c9.id)
a1.team_players.create(player_id: c10.id)
a1.team_players.create(player_id: c11.id)

a2.team_players.create(player_id: d1.id)
a2.team_players.create(player_id: d2.id)
a2.team_players.create(player_id: d3.id)
a2.team_players.create(player_id: d4.id)
a2.team_players.create(player_id: d5.id)
a2.team_players.create(player_id: d6.id)
a2.team_players.create(player_id: d7.id)
a2.team_players.create(player_id: d8.id)
a2.team_players.create(player_id: d9.id)
a2.team_players.create(player_id: d10.id)
a2.team_players.create(player_id: d11.id)

a3.team_players.create(player_id: g1.id)
a3.team_players.create(player_id: g2.id)
a3.team_players.create(player_id: g3.id)
a3.team_players.create(player_id: g4.id)
a3.team_players.create(player_id: g5.id)
a3.team_players.create(player_id: g6.id)
a3.team_players.create(player_id: g7.id)
a3.team_players.create(player_id: g8.id)
a3.team_players.create(player_id: g9.id)
a3.team_players.create(player_id: g10.id)
a3.team_players.create(player_id: g11.id)

# a4.team_players.create(player_id: s1.id)
# a4.team_players.create(player_id: s2.id)
# a4.team_players.create(player_id: s3.id)
# a4.team_players.create(player_id: s4.id)
# a4.team_players.create(player_id: s5.id)
# a4.team_players.create(player_id: s6.id)
# a4.team_players.create(player_id: s7.id)
# a4.team_players.create(player_id: s8.id)
# a4.team_players.create(player_id: s9.id)
# a4.team_players.create(player_id: s10.id)
# a4.team_players.create(player_id: s11.id)

b1.team_players.create(player_id: e1.id)
b1.team_players.create(player_id: e2.id)
b1.team_players.create(player_id: e3.id)
b1.team_players.create(player_id: e4.id)
b1.team_players.create(player_id: e5.id)
b1.team_players.create(player_id: e6.id)
b1.team_players.create(player_id: e7.id)
b1.team_players.create(player_id: e8.id)
b1.team_players.create(player_id: e9.id)
b1.team_players.create(player_id: e10.id)
b1.team_players.create(player_id: e11.id)

b2.team_players.create(player_id: i1.id)
b2.team_players.create(player_id: i2.id)
b2.team_players.create(player_id: i3.id)
b2.team_players.create(player_id: i4.id)
b2.team_players.create(player_id: i5.id)
b2.team_players.create(player_id: i6.id)
b2.team_players.create(player_id: i7.id)
b2.team_players.create(player_id: i8.id)
b2.team_players.create(player_id: i9.id)
b2.team_players.create(player_id: i10.id)
b2.team_players.create(player_id: i11.id)

b3.team_players.create(player_id: p1.id)
b3.team_players.create(player_id: p2.id)
b3.team_players.create(player_id: p3.id)
b3.team_players.create(player_id: p4.id)
b3.team_players.create(player_id: p5.id)
b3.team_players.create(player_id: p6.id)
b3.team_players.create(player_id: p7.id)
b3.team_players.create(player_id: p8.id)
b3.team_players.create(player_id: p9.id)
b3.team_players.create(player_id: p10.id)
b3.team_players.create(player_id: p11.id)

b4.team_players.create(player_id: w1.id)
b4.team_players.create(player_id: w2.id)
b4.team_players.create(player_id: w3.id)
b4.team_players.create(player_id: w4.id)
b4.team_players.create(player_id: w5.id)
b4.team_players.create(player_id: w6.id)
b4.team_players.create(player_id: w7.id)
b4.team_players.create(player_id: w8.id)
b4.team_players.create(player_id: w9.id)
b4.team_players.create(player_id: w10.id)
b4.team_players.create(player_id: w11.id)


